services:
  - type: web
    name: telegram-openai-bot
    env: node
    plan: free
    startCommand: "yarn start"
    envVars:
      - key: TELEGRAM_TOKEN
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: OPENAI_MODEL
        sync: false
      - key: OPEN_AI_ENDPOINT
        sync: false
