FROM eclipse-temurin:25-jre-noble

RUN apt-get update -y && \
    apt-get install -y netcat-traditional && \
    rm -rf /var/lib/apt/lists/*
RUN ln -fs /usr/share/zoneinfo/Europe/Warsaw /etc/localtime && dpkg-reconfigure -f noninteractive tzdata

RUN mkdir -p /app
COPY luxmed-bot/server/build/libs/server.jar /app/server.jar
COPY docker/luxmed-entrypoint.sh /app/luxmed-entrypoint.sh

EXPOSE 8080

CMD ["sh", "/app/luxmed-entrypoint.sh"]
